language: java
script: bash build-travis.sh

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "fSlkzUugexEb9f0TGN3EwWnJLBQSNtBan4D/ABFRFDAofm/NGxTq6wVzW6DnVmcrdqivmMh5gZprCaCutGXihmr+xWgFWeAb/DmFjD+uT70a3qSFYrD3x6m6RdxAQiYfo1+qMsRGoumf6OGt2SGucv2IOxrmbkIz47EAC1INrCSzfvrIxLNCzRrk8vP/1rWxSMjksC9+RUIWBdDiWcI3m81W7Nz+NLPRBMGbEX/MF6ZvB7CSIWGCNGK/GZ+/Z3C6iG0NqJeSDIKqfiPPzYZgiMp+8COZNI5wWxenOgOYVR9dbA12Ms98S/I7W07kYbY+KQrcp3lVPBJIleTkS/Wg/nupyUo+e2Kn3VtR3CfXsHoERdL3Qh7lnS/oYrkPrLTpzk4tbJNdyLyATLs3rIeiDr8ljwf+0RPLsl0TnqvqXRkvrqt53UBq0/se8J+ujg/LpXss+xRXfaryiAwPUr29+OGxPrVDq01iFsHV4pj6mDZOIdTSbSjbWgC9gtg4imMaFFGOnOp3rKfaULMuhJDvtmM+KYto27AjDUaqIWk8eLS7e7ThoqHabg3J8sbI5cPjamSQuk3fZlLlGFetCRn5uiLLpZ/NT2H1uWTk/0zKBN/COiLa8gA37WDSif2DizvAxpwaBC+TjcXdBTuno79j6oF7OCkh5Xlg562QWGgauHw="

addons:
  coverity_scan:
    project:
      name: "ph4r05/Openfire"
      description: "Build submitted via Travis CI"
    notification_email: ph4r05@gmail.com
    build_command_prepend: ant -f build/build.xml clean
    build_command:   ant -f build/build.xml openfire plugins
    branch_pattern: coverity_scan

